###
GET http://localhost:4004/catalog/getJoinVirtualData()

###
GET http://localhost:4004/catalog/view_loginlogs

###
GET http://localhost:4004/catalog/view_USR01
# (mandt = 000, bname = 'BATCH_USER')?$expand=profiles

####
POST http://localhost:4004/catalog/view_USR05
Content-Type: application/json

{
    "mandt": "000",
    "bname": "BATCH_USER",
    "parid": "AAA",
    "parva": "AAA"   
}