module.exports = {
    QUERIES: {
        PROFILES_JOIN_LOGINLOGS: "SELECT * FROM PROFILES JOIN LOGIN_LOGS ON PROFILES.PROFILEID = LOGIN_LOGS.PROFILEID WHERE ROLE = ?"
    },
    TABLES: {
        V_USR02: "V_USR02",
        PROFILES: "PROFILES",
        LOGIN_LOGS: "LOGIN_LOGS"
    }
}