module.exports = {
    QUERIES: {
        PROFILES_JOIN_LOGINLOGS: "SELECT * FROM PROFILES JOIN LOGIN_LOGS ON PROFILES.PROFILEID = LOGIN_LOGS.PROFILEID WHERE ROLE = ?",
        VIRTUAL_JOIN_HANA: `SELECT * FROM V_USR01 JOIN V_USR02 ON V_USR01.MANDT = V_USR02.MANDT AND V_USR01.BNAME = V_USR02.BNAME
            JOIN PROFILES ON PROFILES.USER_MANDT = V_USR01.MANDT AND PROFILES.USER_BNAME = V_USR01.BNAME
            JOIN V_USR04 ON V_USR02.MANDT = V_USR04.MANDT AND V_USR02.BNAME = V_USR04.BNAME
            JOIN V_USR05 ON V_USR04.MANDT = V_USR05.MANDT AND V_USR04.BNAME = V_USR05.BNAME
            WHERE V_USR02.CLASS = ? AND V_USR04.MODBE = ? AND V_USR05.PARVA = ? AND PROFILES.ACTIVE = ? `
    },
    TABLES: {
        V_USR01: "V_USR01",
        V_USR02: "V_USR02",
        V_USR03: "V_USR03",
        V_USR04: "V_USR04",
        V_USR05: "V_USR05",
        PROFILES: "PROFILES",
        LOGIN_LOGS: "LOGIN_LOGS"
    }
}